### ISSUE TITLE
建议放大改为加深阴影

### ISSUE THREAD

**Issue by simowce** [XPoet/hexo-theme-ils#10]
首先，感谢作者写的这个主题，我真的是太喜欢了，这个就是我一直在寻找的极简风格的 Hexo 主题。

然后就是一个建议，目前放到每篇文章或者博客 Header 部分都是有放大，我觉得如果把这个放大的效果去掉，改为加深阴影（虽然目前也有这个效果，但是比较浅），整个主题的气质会上升一个档次。

希望作者大大采纳，或者做一个选项让用户自己选择，您看这么样？

再次感谢。

**Comment by XPoet** [comment]
@simowce 
感谢支持，当前版本有你想要的样式配置选项：
参考如下：
```yml
magic:
  enable: true  
  transform: false  # transform 设为 false 即可关闭放大效果
```
阴影部分这个建议非常好，我会尽快完善，抽离出单独的配置项。

**Comment by simowce** [comment]
> @simowce
> 感谢支持，当前版本有你想要的样式配置选项：
> 参考如下：
> 
> ```yaml
> magic:
>   enable: true  
>   transform: false  # transform 设为 false 即可关闭放大效果
> ```
> 
> 阴影部分这个建议非常好，我会尽快完善，抽离出单独的配置项。

谢谢，十分期待最终效果。

**Comment by XPoet** [comment]
@simowce 
`v1.2.0` 版本已实现鼠标悬浮时缩放和阴影效果的单独配置，请下载最新版本使用。
```yml
# magic theme
magic:
  enable: true
  scale: false # 缩放效果
  shadow: true # 阴影效果
```
