### ISSUE TITLE
代码高亮功能不能正常使用

### ISSUE THREAD

**Issue by Akie-hub** [XPoet/hexo-theme-ils#19]
hexo根目录下的配置文件中代码高亮的配置
```yml
highlight:
  enable: true
  auto_detect: true
  line_number: false
  tab_replace: ''
  wrap: false
  hljs: false
```
按照如上配置，我在使用[pure](https://github.com/cofess/hexo-theme-pure)主题时，一切都正常，当换成hexo-theme-ils时，代码高亮很少，如图![image-20201011122908053](https://i.loli.net/2020/10/11/JEUVmPtXWxekNzd.png)。
当我把```hljs```改为```true```，代码全部变成灰色。目前正在困惑中，怎样才能在不大动配置的情况下，让代码能够通过 hexo 原有方案正常高亮呢。希望得到帮助，谢谢。
