### ISSUE TITLE
搜索模块怎么设置

### ISSUE THREAD

**Issue by leungchiwah** [XPoet/hexo-theme-ils#6]
求教

**Comment by XPoet** [comment]
@leungchiwah 

在主题配置文件  `_config.yml` 里面进行搜索功能相关的配置，`enable` 的值设为  `true` 即可启用。

**注意：搜索功能需额外安装 Hexo 插件 `hexo-generator-searchdb`，在 Hexo 项目根目录下，使用 npm 安装，命令：`npm install hexo-generator-searchdb`。**

参考下我的配置

```yml
local_search:
  enable: true
  trigger: auto
  unescape: false
  preload: true
```

**Comment by leungchiwah** [comment]
请问 主配置文件要配置吗?

**Comment by leungchiwah** [comment]
嗯 这部分都操作都一样,但是主配置文件你怎么设置的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "指间的诗意"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 下午5:36
收件人: "XPoet/hexo-theme-ils"<hexo-theme-ils@noreply.github.com&gt;; 
抄送: "梁子桦"<429612158@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [XPoet/hexo-theme-ils] 搜索模块怎么设置 (#6)





 
@leungchiwah
 
在主题配置文件  _config.yml 里面进行搜索功能相关的配置，enable 的值设为  true 即可启用。
 
注意：搜索功能需额外安装 Hexo 插件 hexo-generator-searchdb，在 Hexo 项目根目录下，使用 npm 安装，命令：npm install hexo-generator-searchdb。
 
参考下我的配置
 local_search:   enable: true   trigger: auto   unescape: false   preload: true

**Comment by XPoet** [comment]
@leungchiwah 
不好意思，主配置文件也需要增加一些配置，搞忘了。
在 Hexo 的配置文件里面增加如下配置就行了
```yml
# Search
## https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.json
  field: post
  content: true
  format: striptags
```

**Comment by XPoet** [comment]
https://github.com/XPoet/xpoet.github.io/blob/hexo/source/_data/_config.yml

**Comment by XPoet** [comment]
我的 Hexo 配置文件参考下：
https://github.com/XPoet/xpoet.github.io/blob/hexo/source/_data/_config.yml

**Comment by leungchiwah** [comment]
好了谢谢,评论模块我也想弄.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"指间的诗意"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午5:56
收件人:&nbsp;"XPoet/hexo-theme-ils"<hexo-theme-ils@noreply.github.com&gt;;
抄送:&nbsp;"梁子桦"<429612158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [XPoet/hexo-theme-ils] 搜索模块怎么设置 (#6)





 
@leungchiwah
 不好意思，主配置文件也需要增加一些配置，搞忘了。
 在 Hexo 的配置文件里面增加如下配置就行了
 # Search ## https://github.com/theme-next/hexo-generator-searchdb search:   path: search.json   field: post   content: true   format: striptags

**Comment by XPoet** [comment]
评论功能只需在主题配置文件里面进行相关的配置
```yml
# comment plugin
# 评论插件，主题内置了 Valine 和 Gitalk，只能使用其中一款，如果 enable 都设为了 true，将使用 Valine。
comments:
  # Valine https://github.com/xCss/Valine
  # 如何使用 Valine 请参考：https://github.com/xCss/Valine
  valine:
    enable: false
    appid:   # 你的 leancloud appid
    appkey:  # 你的 leancloud appkey
    meta: ['nick', 'mail', 'link']  # 评论框要填写的选项
    placeholder: 😜尽情吐槽吧~

  # Gitalk https://github.com/gitalk/gitalk
  # 如何使用 Gitalk 请参考：https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id:      # 你的 GitHub ID
    repository:     # 你的 GitHub 仓库名
    client_id:      # 你的 GitHub Application Client ID
    client_secret:  # 你的 GitHub Application Client Secret
```
